### ISSUE TITLE
Emit an error event to the OTP logger when a service crashes

### ISSUE THREAD

**Issue by lpil** [gleam-experiments/elli#13]

**Comment by fabjan** [comment]
Ah, this is why my failures inside services in Elli are silently lost!

Do you have something structured and Gleam typed in mind for these events, or is an informative Map passed into `?LOG_ERROR` enough?

I could just do the latter and the PR could be a place to discuss alternatives.

If you prefer the former I think we'd need more discussion here first probably.

**Comment by lpil** [comment]
Passing the error into `?LOG_ERROR` sounds fab

**Comment by fabjan** [comment]
Pull request #17 should resolve this I believe. If the logging testing feels too rigid for this library I can just rip that out.

**Comment by fabjan** [comment]
I think this issue can be closed. Must have written the incorrect magic words in #17 that made this not get closed automatically by the merge.

**Comment by lpil** [comment]
Thank you!
