### ISSUE TITLE
Service module deprecation 

### ISSUE THREAD

**Issue by NWBY** [gleam-experiments/elli#20]
Apologies if this isn’t the right place to be asking this question, new to the Gleam community. 

The service module was marked as deprecated not too long ago. What does this mean for this package? Seeing as it relies on the Service type. 

Is it recommended to use Mist or Wisp instead of elli?

**Comment by lpil** [comment]
You can use this library fine if you prefer Elli. The use of the service module needs to be removed.

**Comment by NWBY** [comment]
Thank you for the response @lpil
