### ISSUE TITLE
Handle uppercase headers

### ISSUE THREAD

**Issue by jpagex** [gleam-experiments/elli#5]
The `gleam-lang/http` library seem to need the headers keys to be in lowercase (https://github.com/gleam-lang/http/blob/main/src/gleam/http.gleam#L118).

But `gleam-lang/elli` does not ensure this is always the case.

For example, when running:
```bash
curl -X POST -d '{"hello":"world"}' -H 'Content-Type: application/json' http://localhost:3000
```
The code `http.get_req_header(req, "content-type")` returns `Error(Nil)`.

**Comment by lpil** [comment]
Good catch, thank you for the report

**Comment by jpagex** [comment]
I can make a PR to fix this. Is it OK if we convert all the "keys" in lowercase characters when we call `get_headers`? Or do you think it can be a performance issue?
